name: HBPSC2020_NEST
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - cython
  - rise
  - numpy
  - nest-simulator
  - datrie
  - python=3.7
  - pygments
  - pip
  - pip:
    - docopt
    - snakemake
